[project]
site_name = "Extract Documentation"
site_url = "https://asit-asso.github.io/extract/"
docs_dir = "docs"
site_dir = "site"
repo_url = "https://github.com/asit-asso/extract"
repo_name = "asit-asso/extract"
extra_css = ["stylesheets/extra.css"]
nav = [
	"index.md",
	{"Getting Started" = [
		"getting-started/install.md",
		"getting-started/configure.md",
		"getting-started/network-integration.md",
    	"getting-started/customize.md",
    	"getting-started/cybersecurity-win.md",
    	"getting-started/cybersecurity-linux.md"
	]},
	"features/user-guide.md",
	"features/admin-guide.md",
	{"Dev Guide" = [
		"features/development.md",
		"features/architecture.md"
	]},
	{"How-To" = [
		"how-to/extract-viageo.md",
		"how-to/fme-form.md",
		"how-to/fme-flow.md",
		"how-to/python.md",
		"how-to/qgis-server-atlas.md"
	]},
	{"Miscellaneous" = [
		"misc/viageo-test.md"
	]}
]

[project.theme]
font.text = "Asap"
font.code = "JetBrains Mono"
logo = "assets/asit_extract_couleur.jpg"
favicon = "assets/extract_favicon64.png"
features = [
    "navigation.sections",
	"navigation.tabs",
	"navigation.tabs.sticky",
	"toc.integrate",
	"navigation.path",
	"content.code.copy"
]

[project.theme.palette]
primary = "custom"

[project.theme.icon]
repo = "fontawesome/brands/github"

[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji" 
emoji_generator = "zensical.extensions.emoji.to_svg"

[project.markdown_extensions.attr_list]
[project.markdown_extensions.admonition]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.superfences]
[project.markdown_extensions.tables]